// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file common.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__INCLINATION_IDL_EX_COMMON_HPP
#define FAST_DDS_GENERATED__INCLINATION_IDL_EX_COMMON_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COMMON_SOURCE)
#define COMMON_DllAPI __declspec( dllexport )
#else
#define COMMON_DllAPI __declspec( dllimport )
#endif // COMMON_SOURCE
#else
#define COMMON_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COMMON_DllAPI
#endif // _WIN32

namespace inclination {

namespace idl_ex {

typedef double value_t;

typedef double timestamp_t;

/*!
 * @brief This class represents the structure Dummy defined by the user in the IDL file.
 * @ingroup common
 */
class Dummy
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Dummy()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Dummy()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Dummy that will be copied.
     */
    eProsima_user_DllExport Dummy(
            const Dummy& x)
    {
        static_cast<void>(x);
    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Dummy that will be copied.
     */
    eProsima_user_DllExport Dummy(
            Dummy&& x) noexcept
    {
        static_cast<void>(x);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Dummy that will be copied.
     */
    eProsima_user_DllExport Dummy& operator =(
            const Dummy& x)
    {

        static_cast<void>(x);

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Dummy that will be copied.
     */
    eProsima_user_DllExport Dummy& operator =(
            Dummy&& x) noexcept
    {

        static_cast<void>(x);

        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Dummy object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Dummy& x) const
    {
        static_cast<void>(x);
        return true;
    }

    /*!
     * @brief Comparison operator.
     * @param x Dummy object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Dummy& x) const
    {
        return !(*this == x);
    }



private:


};

} // namespace idl_ex

} // namespace inclination

#endif // _FAST_DDS_GENERATED_INCLINATION_IDL_EX_COMMON_HPP_


