// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file commonTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "commonTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "common.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace inclination {
namespace idl_ex {
void register_value_t_type_identifier(
        TypeIdentifierPair& type_ids_value_t)
{
    ReturnCode_t return_code_value_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_value_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::value_t", type_ids_value_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_value_t)
    {
        AliasTypeFlag alias_flags_value_t = 0;
        QualifiedTypeName type_name_value_t = "inclination::idl_ex::value_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_value_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_value_t;
        CompleteTypeDetail detail_value_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_value_t, ann_custom_value_t, type_name_value_t.to_string());
        CompleteAliasHeader header_value_t = TypeObjectUtils::build_complete_alias_header(detail_value_t);
        AliasMemberFlag related_flags_value_t = 0;
        return_code_value_t =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "_double", type_ids_value_t);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_value_t)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::value_t related TypeIdentifier unknown to TypeObjectRegistry.");
            return;
        }
        bool common_value_t_ec {false};
        CommonAliasBody common_value_t {TypeObjectUtils::build_common_alias_body(related_flags_value_t,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_value_t, common_value_t_ec))};
        if (!common_value_t_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "inclination::idl_ex::value_t related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_value_t;
        ann_custom_value_t.reset();
        CompleteAliasBody body_value_t = TypeObjectUtils::build_complete_alias_body(common_value_t,
                member_ann_builtin_value_t, ann_custom_value_t);
        CompleteAliasType alias_type_value_t = TypeObjectUtils::build_complete_alias_type(alias_flags_value_t,
                header_value_t, body_value_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_value_t,
                    type_name_value_t.to_string(), type_ids_value_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "inclination::idl_ex::value_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}

void register_timestamp_t_type_identifier(
        TypeIdentifierPair& type_ids_timestamp_t)
{
    ReturnCode_t return_code_timestamp_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_timestamp_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::timestamp_t", type_ids_timestamp_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_t)
    {
        AliasTypeFlag alias_flags_timestamp_t = 0;
        QualifiedTypeName type_name_timestamp_t = "inclination::idl_ex::timestamp_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_timestamp_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_timestamp_t;
        CompleteTypeDetail detail_timestamp_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_timestamp_t, ann_custom_timestamp_t, type_name_timestamp_t.to_string());
        CompleteAliasHeader header_timestamp_t = TypeObjectUtils::build_complete_alias_header(detail_timestamp_t);
        AliasMemberFlag related_flags_timestamp_t = 0;
        return_code_timestamp_t =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "_double", type_ids_timestamp_t);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_t)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::timestamp_t related TypeIdentifier unknown to TypeObjectRegistry.");
            return;
        }
        bool common_timestamp_t_ec {false};
        CommonAliasBody common_timestamp_t {TypeObjectUtils::build_common_alias_body(related_flags_timestamp_t,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_t, common_timestamp_t_ec))};
        if (!common_timestamp_t_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "inclination::idl_ex::timestamp_t related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_t;
        ann_custom_timestamp_t.reset();
        CompleteAliasBody body_timestamp_t = TypeObjectUtils::build_complete_alias_body(common_timestamp_t,
                member_ann_builtin_timestamp_t, ann_custom_timestamp_t);
        CompleteAliasType alias_type_timestamp_t = TypeObjectUtils::build_complete_alias_type(alias_flags_timestamp_t,
                header_timestamp_t, body_timestamp_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_timestamp_t,
                    type_name_timestamp_t.to_string(), type_ids_timestamp_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "inclination::idl_ex::timestamp_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Dummy_type_identifier(
        TypeIdentifierPair& type_ids_Dummy)
{

    ReturnCode_t return_code_Dummy {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Dummy =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::Dummy", type_ids_Dummy);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Dummy)
    {
        StructTypeFlag struct_flags_Dummy = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Dummy = "inclination::idl_ex::Dummy";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Dummy;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Dummy;
        CompleteTypeDetail detail_Dummy = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Dummy, ann_custom_Dummy, type_name_Dummy.to_string());
        CompleteStructHeader header_Dummy;
        header_Dummy = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Dummy);
        CompleteStructMemberSeq member_seq_Dummy;
        CompleteStructType struct_type_Dummy = TypeObjectUtils::build_complete_struct_type(struct_flags_Dummy, header_Dummy, member_seq_Dummy);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Dummy, type_name_Dummy.to_string(), type_ids_Dummy))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::Dummy already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace idl_ex

} // namespace inclination

