// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ohlcvPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "ohlcvPubSubTypes.hpp"

#include <fastdds/dds/log/Log.hpp>
#include <fastdds/rtps/common/CdrSerialization.hpp>

#include "ohlcvCdrAux.hpp"
#include "ohlcvTypeObjectSupport.hpp"

using SerializedPayload_t = eprosima::fastdds::rtps::SerializedPayload_t;
using InstanceHandle_t = eprosima::fastdds::rtps::InstanceHandle_t;
using DataRepresentationId_t = eprosima::fastdds::dds::DataRepresentationId_t;

namespace inclination {
    namespace idl_ex {
        exchange_tPubSubType::exchange_tPubSubType()
        {
            set_name("inclination::idl_ex::exchange_t");
            uint32_t type_size = inclination_idl_ex_exchange_t_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_exchange_t_max_key_cdr_typesize > 16 ? inclination_idl_ex_exchange_t_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        exchange_tPubSubType::~exchange_tPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool exchange_tPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::exchange_t* p_type = static_cast<const ::inclination::idl_ex::exchange_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool exchange_tPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::exchange_t* p_type = static_cast<::inclination::idl_ex::exchange_t*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t exchange_tPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::exchange_t*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* exchange_tPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::exchange_t());
        }

        void exchange_tPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::exchange_t*>(data));
        }

        bool exchange_tPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::exchange_t data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool exchange_tPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::exchange_t* p_type = static_cast<const ::inclination::idl_ex::exchange_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_exchange_t_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_exchange_t_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void exchange_tPubSubType::register_type_object_representation()
        {
            register_exchange_t_type_identifier(type_identifiers_);
        }

        asset_tPubSubType::asset_tPubSubType()
        {
            set_name("inclination::idl_ex::asset_t");
            uint32_t type_size = inclination_idl_ex_asset_t_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_asset_t_max_key_cdr_typesize > 16 ? inclination_idl_ex_asset_t_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        asset_tPubSubType::~asset_tPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool asset_tPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::asset_t* p_type = static_cast<const ::inclination::idl_ex::asset_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool asset_tPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::asset_t* p_type = static_cast<::inclination::idl_ex::asset_t*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t asset_tPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::asset_t*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* asset_tPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::asset_t());
        }

        void asset_tPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::asset_t*>(data));
        }

        bool asset_tPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::asset_t data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool asset_tPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::asset_t* p_type = static_cast<const ::inclination::idl_ex::asset_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_asset_t_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_asset_t_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void asset_tPubSubType::register_type_object_representation()
        {
            register_asset_t_type_identifier(type_identifiers_);
        }

        symbol_tPubSubType::symbol_tPubSubType()
        {
            set_name("inclination::idl_ex::symbol_t");
            uint32_t type_size = inclination_idl_ex_symbol_t_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_symbol_t_max_key_cdr_typesize > 16 ? inclination_idl_ex_symbol_t_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        symbol_tPubSubType::~symbol_tPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool symbol_tPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::symbol_t* p_type = static_cast<const ::inclination::idl_ex::symbol_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool symbol_tPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::symbol_t* p_type = static_cast<::inclination::idl_ex::symbol_t*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t symbol_tPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::symbol_t*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* symbol_tPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::symbol_t());
        }

        void symbol_tPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::symbol_t*>(data));
        }

        bool symbol_tPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::symbol_t data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool symbol_tPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::symbol_t* p_type = static_cast<const ::inclination::idl_ex::symbol_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_symbol_t_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_symbol_t_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void symbol_tPubSubType::register_type_object_representation()
        {
            register_symbol_t_type_identifier(type_identifiers_);
        }

        interval_tPubSubType::interval_tPubSubType()
        {
            set_name("inclination::idl_ex::interval_t");
            uint32_t type_size = inclination_idl_ex_interval_t_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_interval_t_max_key_cdr_typesize > 16 ? inclination_idl_ex_interval_t_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        interval_tPubSubType::~interval_tPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool interval_tPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::interval_t* p_type = static_cast<const ::inclination::idl_ex::interval_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool interval_tPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::interval_t* p_type = static_cast<::inclination::idl_ex::interval_t*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t interval_tPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::interval_t*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* interval_tPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::interval_t());
        }

        void interval_tPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::interval_t*>(data));
        }

        bool interval_tPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::interval_t data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool interval_tPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::interval_t* p_type = static_cast<const ::inclination::idl_ex::interval_t*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_interval_t_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_interval_t_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void interval_tPubSubType::register_type_object_representation()
        {
            register_interval_t_type_identifier(type_identifiers_);
        }

        OhlcvDataPubSubType::OhlcvDataPubSubType()
        {
            set_name("inclination::idl_ex::OhlcvData");
            uint32_t type_size = inclination_idl_ex_OhlcvData_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_OhlcvData_max_key_cdr_typesize > 16 ? inclination_idl_ex_OhlcvData_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        OhlcvDataPubSubType::~OhlcvDataPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool OhlcvDataPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::OhlcvData* p_type = static_cast<const ::inclination::idl_ex::OhlcvData*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool OhlcvDataPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::OhlcvData* p_type = static_cast<::inclination::idl_ex::OhlcvData*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t OhlcvDataPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::OhlcvData*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* OhlcvDataPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::OhlcvData());
        }

        void OhlcvDataPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::OhlcvData*>(data));
        }

        bool OhlcvDataPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::OhlcvData data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool OhlcvDataPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::OhlcvData* p_type = static_cast<const ::inclination::idl_ex::OhlcvData*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_OhlcvData_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_OhlcvData_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void OhlcvDataPubSubType::register_type_object_representation()
        {
            register_OhlcvData_type_identifier(type_identifiers_);
        }

        OhlcvPubSubType::OhlcvPubSubType()
        {
            set_name("inclination::idl_ex::Ohlcv");
            uint32_t type_size = inclination_idl_ex_Ohlcv_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_Ohlcv_max_key_cdr_typesize > 16 ? inclination_idl_ex_Ohlcv_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        OhlcvPubSubType::~OhlcvPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool OhlcvPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::Ohlcv* p_type = static_cast<const ::inclination::idl_ex::Ohlcv*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool OhlcvPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::Ohlcv* p_type = static_cast<::inclination::idl_ex::Ohlcv*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t OhlcvPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::Ohlcv*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* OhlcvPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::Ohlcv());
        }

        void OhlcvPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::Ohlcv*>(data));
        }

        bool OhlcvPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::Ohlcv data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool OhlcvPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::Ohlcv* p_type = static_cast<const ::inclination::idl_ex::Ohlcv*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_Ohlcv_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_Ohlcv_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void OhlcvPubSubType::register_type_object_representation()
        {
            register_Ohlcv_type_identifier(type_identifiers_);
        }

        OhlcvSeriesPubSubType::OhlcvSeriesPubSubType()
        {
            set_name("inclination::idl_ex::OhlcvSeries");
            uint32_t type_size = inclination_idl_ex_OhlcvSeries_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = inclination_idl_ex_OhlcvSeries_max_key_cdr_typesize > 16 ? inclination_idl_ex_OhlcvSeries_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        OhlcvSeriesPubSubType::~OhlcvSeriesPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool OhlcvSeriesPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ::inclination::idl_ex::OhlcvSeries* p_type = static_cast<const ::inclination::idl_ex::OhlcvSeries*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool OhlcvSeriesPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ::inclination::idl_ex::OhlcvSeries* p_type = static_cast<::inclination::idl_ex::OhlcvSeries*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t OhlcvSeriesPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ::inclination::idl_ex::OhlcvSeries*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* OhlcvSeriesPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ::inclination::idl_ex::OhlcvSeries());
        }

        void OhlcvSeriesPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<::inclination::idl_ex::OhlcvSeries*>(data));
        }

        bool OhlcvSeriesPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ::inclination::idl_ex::OhlcvSeries data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool OhlcvSeriesPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ::inclination::idl_ex::OhlcvSeries* p_type = static_cast<const ::inclination::idl_ex::OhlcvSeries*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    inclination_idl_ex_OhlcvSeries_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || inclination_idl_ex_OhlcvSeries_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void OhlcvSeriesPubSubType::register_type_object_representation()
        {
            register_OhlcvSeries_type_identifier(type_identifiers_);
        }

    } // namespace idl_ex

} // namespace inclination


// Include auxiliary functions like for serializing/deserializing.
#include "ohlcvCdrAux.ipp"
