// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ohlcvTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "ohlcvTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "ohlcv.hpp"

#include "common.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace inclination {
namespace idl_ex {
void register_key_t_type_identifier(
        TypeIdentifierPair& type_ids_key_t)
{
    ReturnCode_t return_code_key_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_key_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::key_t", type_ids_key_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_key_t)
    {
        AliasTypeFlag alias_flags_key_t = 0;
        QualifiedTypeName type_name_key_t = "inclination::idl_ex::key_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_key_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_key_t;
        CompleteTypeDetail detail_key_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_key_t, ann_custom_key_t, type_name_key_t.to_string());
        CompleteAliasHeader header_key_t = TypeObjectUtils::build_complete_alias_header(detail_key_t);
        AliasMemberFlag related_flags_key_t = 0;
        return_code_key_t =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_string_unbounded", type_ids_key_t);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_key_t)
        {
            {
                SBound bound = 0;
                StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                        "anonymous_string_unbounded", type_ids_key_t))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_key_t_ec {false};
        CommonAliasBody common_key_t {TypeObjectUtils::build_common_alias_body(related_flags_key_t,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_key_t, common_key_t_ec))};
        if (!common_key_t_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "inclination::idl_ex::key_t related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_key_t;
        ann_custom_key_t.reset();
        CompleteAliasBody body_key_t = TypeObjectUtils::build_complete_alias_body(common_key_t,
                member_ann_builtin_key_t, ann_custom_key_t);
        CompleteAliasType alias_type_key_t = TypeObjectUtils::build_complete_alias_type(alias_flags_key_t,
                header_key_t, body_key_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_key_t,
                    type_name_key_t.to_string(), type_ids_key_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "inclination::idl_ex::key_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}

void register_price_t_type_identifier(
        TypeIdentifierPair& type_ids_price_t)
{
    ReturnCode_t return_code_price_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_price_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::price_t", type_ids_price_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_price_t)
    {
        AliasTypeFlag alias_flags_price_t = 0;
        QualifiedTypeName type_name_price_t = "inclination::idl_ex::price_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_price_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_price_t;
        CompleteTypeDetail detail_price_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_price_t, ann_custom_price_t, type_name_price_t.to_string());
        CompleteAliasHeader header_price_t = TypeObjectUtils::build_complete_alias_header(detail_price_t);
        AliasMemberFlag related_flags_price_t = 0;
        return_code_price_t =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "_double", type_ids_price_t);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_price_t)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::price_t related TypeIdentifier unknown to TypeObjectRegistry.");
            return;
        }
        bool common_price_t_ec {false};
        CommonAliasBody common_price_t {TypeObjectUtils::build_common_alias_body(related_flags_price_t,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_price_t, common_price_t_ec))};
        if (!common_price_t_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "inclination::idl_ex::price_t related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_price_t;
        ann_custom_price_t.reset();
        CompleteAliasBody body_price_t = TypeObjectUtils::build_complete_alias_body(common_price_t,
                member_ann_builtin_price_t, ann_custom_price_t);
        CompleteAliasType alias_type_price_t = TypeObjectUtils::build_complete_alias_type(alias_flags_price_t,
                header_price_t, body_price_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_price_t,
                    type_name_price_t.to_string(), type_ids_price_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "inclination::idl_ex::price_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}

void register_volume_t_type_identifier(
        TypeIdentifierPair& type_ids_volume_t)
{
    ReturnCode_t return_code_volume_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_volume_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::volume_t", type_ids_volume_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_volume_t)
    {
        AliasTypeFlag alias_flags_volume_t = 0;
        QualifiedTypeName type_name_volume_t = "inclination::idl_ex::volume_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_volume_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_volume_t;
        CompleteTypeDetail detail_volume_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_volume_t, ann_custom_volume_t, type_name_volume_t.to_string());
        CompleteAliasHeader header_volume_t = TypeObjectUtils::build_complete_alias_header(detail_volume_t);
        AliasMemberFlag related_flags_volume_t = 0;
        return_code_volume_t =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "_double", type_ids_volume_t);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_volume_t)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::volume_t related TypeIdentifier unknown to TypeObjectRegistry.");
            return;
        }
        bool common_volume_t_ec {false};
        CommonAliasBody common_volume_t {TypeObjectUtils::build_common_alias_body(related_flags_volume_t,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_volume_t, common_volume_t_ec))};
        if (!common_volume_t_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "inclination::idl_ex::volume_t related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_volume_t;
        ann_custom_volume_t.reset();
        CompleteAliasBody body_volume_t = TypeObjectUtils::build_complete_alias_body(common_volume_t,
                member_ann_builtin_volume_t, ann_custom_volume_t);
        CompleteAliasType alias_type_volume_t = TypeObjectUtils::build_complete_alias_type(alias_flags_volume_t,
                header_volume_t, body_volume_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_volume_t,
                    type_name_volume_t.to_string(), type_ids_volume_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "inclination::idl_ex::volume_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_exchange_t_type_identifier(
        TypeIdentifierPair& type_ids_exchange_t)
{

    ReturnCode_t return_code_exchange_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_exchange_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::exchange_t", type_ids_exchange_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_exchange_t)
    {
        StructTypeFlag struct_flags_exchange_t = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_exchange_t = "inclination::idl_ex::exchange_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_exchange_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_exchange_t;
        CompleteTypeDetail detail_exchange_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_exchange_t, ann_custom_exchange_t, type_name_exchange_t.to_string());
        CompleteStructHeader header_exchange_t;
        header_exchange_t = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_exchange_t);
        CompleteStructMemberSeq member_seq_exchange_t;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_id);
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_exchange_t.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_exchange_t);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_exchange_t, member_id);
        }
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000001;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_exchange_t.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_exchange_t);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_exchange_t, member_name);
        }
        CompleteStructType struct_type_exchange_t = TypeObjectUtils::build_complete_struct_type(struct_flags_exchange_t, header_exchange_t, member_seq_exchange_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_exchange_t, type_name_exchange_t.to_string(), type_ids_exchange_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::exchange_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_asset_t_type_identifier(
        TypeIdentifierPair& type_ids_asset_t)
{

    ReturnCode_t return_code_asset_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_asset_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::asset_t", type_ids_asset_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_asset_t)
    {
        StructTypeFlag struct_flags_asset_t = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_asset_t = "inclination::idl_ex::asset_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_asset_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_asset_t;
        CompleteTypeDetail detail_asset_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_asset_t, ann_custom_asset_t, type_name_asset_t.to_string());
        CompleteStructHeader header_asset_t;
        header_asset_t = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_asset_t);
        CompleteStructMemberSeq member_seq_asset_t;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_id);
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_asset_t.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_asset_t);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_asset_t, member_id);
        }
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000001;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_asset_t.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_asset_t);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_asset_t, member_name);
        }
        CompleteStructType struct_type_asset_t = TypeObjectUtils::build_complete_struct_type(struct_flags_asset_t, header_asset_t, member_seq_asset_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_asset_t, type_name_asset_t.to_string(), type_ids_asset_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::asset_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_symbol_t_type_identifier(
        TypeIdentifierPair& type_ids_symbol_t)
{

    ReturnCode_t return_code_symbol_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_symbol_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::symbol_t", type_ids_symbol_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_symbol_t)
    {
        StructTypeFlag struct_flags_symbol_t = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_symbol_t = "inclination::idl_ex::symbol_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_symbol_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_symbol_t;
        CompleteTypeDetail detail_symbol_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_symbol_t, ann_custom_symbol_t, type_name_symbol_t.to_string());
        CompleteStructHeader header_symbol_t;
        header_symbol_t = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_symbol_t);
        CompleteStructMemberSeq member_seq_symbol_t;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_id);
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_symbol_t.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_symbol_t);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_symbol_t, member_id);
        }
        {
            TypeIdentifierPair type_ids_base;
            ReturnCode_t return_code_base {eprosima::fastdds::dds::RETCODE_OK};
            return_code_base =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::asset_t", type_ids_base);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_base)
            {
                ::inclination::idl_ex::register_asset_t_type_identifier(type_ids_base);
            }
            StructMemberFlag member_flags_base = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_base = 0x00000001;
            bool common_base_ec {false};
            CommonStructMember common_base {TypeObjectUtils::build_common_struct_member(member_id_base, member_flags_base, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_base, common_base_ec))};
            if (!common_base_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure base member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_base = "base";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_base;
            ann_custom_symbol_t.reset();
            CompleteMemberDetail detail_base = TypeObjectUtils::build_complete_member_detail(name_base, member_ann_builtin_base, ann_custom_symbol_t);
            CompleteStructMember member_base = TypeObjectUtils::build_complete_struct_member(common_base, detail_base);
            TypeObjectUtils::add_complete_struct_member(member_seq_symbol_t, member_base);
        }
        {
            TypeIdentifierPair type_ids_quote;
            ReturnCode_t return_code_quote {eprosima::fastdds::dds::RETCODE_OK};
            return_code_quote =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::asset_t", type_ids_quote);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_quote)
            {
                ::inclination::idl_ex::register_asset_t_type_identifier(type_ids_quote);
            }
            StructMemberFlag member_flags_quote = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_quote = 0x00000002;
            bool common_quote_ec {false};
            CommonStructMember common_quote {TypeObjectUtils::build_common_struct_member(member_id_quote, member_flags_quote, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_quote, common_quote_ec))};
            if (!common_quote_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure quote member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_quote = "quote";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_quote;
            ann_custom_symbol_t.reset();
            CompleteMemberDetail detail_quote = TypeObjectUtils::build_complete_member_detail(name_quote, member_ann_builtin_quote, ann_custom_symbol_t);
            CompleteStructMember member_quote = TypeObjectUtils::build_complete_struct_member(common_quote, detail_quote);
            TypeObjectUtils::add_complete_struct_member(member_seq_symbol_t, member_quote);
        }
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000003;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_symbol_t.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_symbol_t);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_symbol_t, member_name);
        }
        CompleteStructType struct_type_symbol_t = TypeObjectUtils::build_complete_struct_type(struct_flags_symbol_t, header_symbol_t, member_seq_symbol_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_symbol_t, type_name_symbol_t.to_string(), type_ids_symbol_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::symbol_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_interval_t_type_identifier(
        TypeIdentifierPair& type_ids_interval_t)
{

    ReturnCode_t return_code_interval_t {eprosima::fastdds::dds::RETCODE_OK};
    return_code_interval_t =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::interval_t", type_ids_interval_t);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_interval_t)
    {
        StructTypeFlag struct_flags_interval_t = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_interval_t = "inclination::idl_ex::interval_t";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_interval_t;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_interval_t;
        CompleteTypeDetail detail_interval_t = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_interval_t, ann_custom_interval_t, type_name_interval_t.to_string());
        CompleteStructHeader header_interval_t;
        header_interval_t = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_interval_t);
        CompleteStructMemberSeq member_seq_interval_t;
        {
            TypeIdentifierPair type_ids_id;
            ReturnCode_t return_code_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_id);
            }
            StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_id = 0x00000000;
            bool common_id_ec {false};
            CommonStructMember common_id {TypeObjectUtils::build_common_struct_member(member_id_id, member_flags_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
            if (!common_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_id = "id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
            ann_custom_interval_t.reset();
            CompleteMemberDetail detail_id = TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_interval_t);
            CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_interval_t, member_id);
        }
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000001;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_interval_t.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_interval_t);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_interval_t, member_name);
        }
        CompleteStructType struct_type_interval_t = TypeObjectUtils::build_complete_struct_type(struct_flags_interval_t, header_interval_t, member_seq_interval_t);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_interval_t, type_name_interval_t.to_string(), type_ids_interval_t))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::interval_t already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_OhlcvData_type_identifier(
        TypeIdentifierPair& type_ids_OhlcvData)
{

    ReturnCode_t return_code_OhlcvData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_OhlcvData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::OhlcvData", type_ids_OhlcvData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_OhlcvData)
    {
        StructTypeFlag struct_flags_OhlcvData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_OhlcvData = "inclination::idl_ex::OhlcvData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_OhlcvData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_OhlcvData;
        CompleteTypeDetail detail_OhlcvData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_OhlcvData, ann_custom_OhlcvData, type_name_OhlcvData.to_string());
        CompleteStructHeader header_OhlcvData;
        header_OhlcvData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_OhlcvData);
        CompleteStructMemberSeq member_seq_OhlcvData;
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::timestamp_t", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                ::inclination::idl_ex::register_timestamp_t_type_identifier(type_ids_timestamp);
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000000;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_OhlcvData.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_OhlcvData);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvData, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_open;
            ReturnCode_t return_code_open {eprosima::fastdds::dds::RETCODE_OK};
            return_code_open =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::price_t", type_ids_open);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_open)
            {
                ::inclination::idl_ex::register_price_t_type_identifier(type_ids_open);
            }
            StructMemberFlag member_flags_open = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_open = 0x00000001;
            bool common_open_ec {false};
            CommonStructMember common_open {TypeObjectUtils::build_common_struct_member(member_id_open, member_flags_open, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_open, common_open_ec))};
            if (!common_open_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure open member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_open = "open";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_open;
            ann_custom_OhlcvData.reset();
            CompleteMemberDetail detail_open = TypeObjectUtils::build_complete_member_detail(name_open, member_ann_builtin_open, ann_custom_OhlcvData);
            CompleteStructMember member_open = TypeObjectUtils::build_complete_struct_member(common_open, detail_open);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvData, member_open);
        }
        {
            TypeIdentifierPair type_ids_high;
            ReturnCode_t return_code_high {eprosima::fastdds::dds::RETCODE_OK};
            return_code_high =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::price_t", type_ids_high);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_high)
            {
                ::inclination::idl_ex::register_price_t_type_identifier(type_ids_high);
            }
            StructMemberFlag member_flags_high = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_high = 0x00000002;
            bool common_high_ec {false};
            CommonStructMember common_high {TypeObjectUtils::build_common_struct_member(member_id_high, member_flags_high, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_high, common_high_ec))};
            if (!common_high_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure high member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_high = "high";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_high;
            ann_custom_OhlcvData.reset();
            CompleteMemberDetail detail_high = TypeObjectUtils::build_complete_member_detail(name_high, member_ann_builtin_high, ann_custom_OhlcvData);
            CompleteStructMember member_high = TypeObjectUtils::build_complete_struct_member(common_high, detail_high);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvData, member_high);
        }
        {
            TypeIdentifierPair type_ids_low;
            ReturnCode_t return_code_low {eprosima::fastdds::dds::RETCODE_OK};
            return_code_low =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::price_t", type_ids_low);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_low)
            {
                ::inclination::idl_ex::register_price_t_type_identifier(type_ids_low);
            }
            StructMemberFlag member_flags_low = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_low = 0x00000003;
            bool common_low_ec {false};
            CommonStructMember common_low {TypeObjectUtils::build_common_struct_member(member_id_low, member_flags_low, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_low, common_low_ec))};
            if (!common_low_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure low member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_low = "low";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_low;
            ann_custom_OhlcvData.reset();
            CompleteMemberDetail detail_low = TypeObjectUtils::build_complete_member_detail(name_low, member_ann_builtin_low, ann_custom_OhlcvData);
            CompleteStructMember member_low = TypeObjectUtils::build_complete_struct_member(common_low, detail_low);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvData, member_low);
        }
        {
            TypeIdentifierPair type_ids_close;
            ReturnCode_t return_code_close {eprosima::fastdds::dds::RETCODE_OK};
            return_code_close =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::price_t", type_ids_close);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_close)
            {
                ::inclination::idl_ex::register_price_t_type_identifier(type_ids_close);
            }
            StructMemberFlag member_flags_close = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_close = 0x00000004;
            bool common_close_ec {false};
            CommonStructMember common_close {TypeObjectUtils::build_common_struct_member(member_id_close, member_flags_close, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_close, common_close_ec))};
            if (!common_close_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure close member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_close = "close";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_close;
            ann_custom_OhlcvData.reset();
            CompleteMemberDetail detail_close = TypeObjectUtils::build_complete_member_detail(name_close, member_ann_builtin_close, ann_custom_OhlcvData);
            CompleteStructMember member_close = TypeObjectUtils::build_complete_struct_member(common_close, detail_close);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvData, member_close);
        }
        {
            TypeIdentifierPair type_ids_volume;
            ReturnCode_t return_code_volume {eprosima::fastdds::dds::RETCODE_OK};
            return_code_volume =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::volume_t", type_ids_volume);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_volume)
            {
                ::inclination::idl_ex::register_volume_t_type_identifier(type_ids_volume);
            }
            StructMemberFlag member_flags_volume = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_volume = 0x00000005;
            bool common_volume_ec {false};
            CommonStructMember common_volume {TypeObjectUtils::build_common_struct_member(member_id_volume, member_flags_volume, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_volume, common_volume_ec))};
            if (!common_volume_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure volume member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_volume = "volume";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_volume;
            ann_custom_OhlcvData.reset();
            CompleteMemberDetail detail_volume = TypeObjectUtils::build_complete_member_detail(name_volume, member_ann_builtin_volume, ann_custom_OhlcvData);
            CompleteStructMember member_volume = TypeObjectUtils::build_complete_struct_member(common_volume, detail_volume);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvData, member_volume);
        }
        CompleteStructType struct_type_OhlcvData = TypeObjectUtils::build_complete_struct_type(struct_flags_OhlcvData, header_OhlcvData, member_seq_OhlcvData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_OhlcvData, type_name_OhlcvData.to_string(), type_ids_OhlcvData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::OhlcvData already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Ohlcv_type_identifier(
        TypeIdentifierPair& type_ids_Ohlcv)
{

    ReturnCode_t return_code_Ohlcv {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Ohlcv =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::Ohlcv", type_ids_Ohlcv);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Ohlcv)
    {
        StructTypeFlag struct_flags_Ohlcv = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Ohlcv = "inclination::idl_ex::Ohlcv";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Ohlcv;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Ohlcv;
        CompleteTypeDetail detail_Ohlcv = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Ohlcv, ann_custom_Ohlcv, type_name_Ohlcv.to_string());
        CompleteStructHeader header_Ohlcv;
        header_Ohlcv = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Ohlcv);
        CompleteStructMemberSeq member_seq_Ohlcv;
        {
            TypeIdentifierPair type_ids_exchange_id;
            ReturnCode_t return_code_exchange_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_exchange_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_exchange_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_exchange_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_exchange_id);
            }
            StructMemberFlag member_flags_exchange_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_exchange_id = 0x00000000;
            bool common_exchange_id_ec {false};
            CommonStructMember common_exchange_id {TypeObjectUtils::build_common_struct_member(member_id_exchange_id, member_flags_exchange_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_exchange_id, common_exchange_id_ec))};
            if (!common_exchange_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure exchange_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_exchange_id = "exchange_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_exchange_id;
            ann_custom_Ohlcv.reset();
            AppliedAnnotationSeq tmp_ann_custom_exchange_id;
            eprosima::fastcdr::optional<std::string> unit_exchange_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_exchange_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_exchange_id;
            eprosima::fastcdr::optional<std::string> hash_id_exchange_id;
            if (unit_exchange_id.has_value() || min_exchange_id.has_value() || max_exchange_id.has_value() || hash_id_exchange_id.has_value())
            {
                member_ann_builtin_exchange_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_exchange_id, min_exchange_id, max_exchange_id, hash_id_exchange_id);
            }
            if (!tmp_ann_custom_exchange_id.empty())
            {
                ann_custom_Ohlcv = tmp_ann_custom_exchange_id;
            }
            CompleteMemberDetail detail_exchange_id = TypeObjectUtils::build_complete_member_detail(name_exchange_id, member_ann_builtin_exchange_id, ann_custom_Ohlcv);
            CompleteStructMember member_exchange_id = TypeObjectUtils::build_complete_struct_member(common_exchange_id, detail_exchange_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Ohlcv, member_exchange_id);
        }
        {
            TypeIdentifierPair type_ids_symbol_id;
            ReturnCode_t return_code_symbol_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_symbol_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_symbol_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_symbol_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_symbol_id);
            }
            StructMemberFlag member_flags_symbol_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_symbol_id = 0x00000001;
            bool common_symbol_id_ec {false};
            CommonStructMember common_symbol_id {TypeObjectUtils::build_common_struct_member(member_id_symbol_id, member_flags_symbol_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_symbol_id, common_symbol_id_ec))};
            if (!common_symbol_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure symbol_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_symbol_id = "symbol_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_symbol_id;
            ann_custom_Ohlcv.reset();
            AppliedAnnotationSeq tmp_ann_custom_symbol_id;
            eprosima::fastcdr::optional<std::string> unit_symbol_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_symbol_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_symbol_id;
            eprosima::fastcdr::optional<std::string> hash_id_symbol_id;
            if (unit_symbol_id.has_value() || min_symbol_id.has_value() || max_symbol_id.has_value() || hash_id_symbol_id.has_value())
            {
                member_ann_builtin_symbol_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_symbol_id, min_symbol_id, max_symbol_id, hash_id_symbol_id);
            }
            if (!tmp_ann_custom_symbol_id.empty())
            {
                ann_custom_Ohlcv = tmp_ann_custom_symbol_id;
            }
            CompleteMemberDetail detail_symbol_id = TypeObjectUtils::build_complete_member_detail(name_symbol_id, member_ann_builtin_symbol_id, ann_custom_Ohlcv);
            CompleteStructMember member_symbol_id = TypeObjectUtils::build_complete_struct_member(common_symbol_id, detail_symbol_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Ohlcv, member_symbol_id);
        }
        {
            TypeIdentifierPair type_ids_interval_id;
            ReturnCode_t return_code_interval_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_interval_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_interval_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_interval_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_interval_id);
            }
            StructMemberFlag member_flags_interval_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_interval_id = 0x00000002;
            bool common_interval_id_ec {false};
            CommonStructMember common_interval_id {TypeObjectUtils::build_common_struct_member(member_id_interval_id, member_flags_interval_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_interval_id, common_interval_id_ec))};
            if (!common_interval_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure interval_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_interval_id = "interval_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_interval_id;
            ann_custom_Ohlcv.reset();
            AppliedAnnotationSeq tmp_ann_custom_interval_id;
            eprosima::fastcdr::optional<std::string> unit_interval_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_interval_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_interval_id;
            eprosima::fastcdr::optional<std::string> hash_id_interval_id;
            if (unit_interval_id.has_value() || min_interval_id.has_value() || max_interval_id.has_value() || hash_id_interval_id.has_value())
            {
                member_ann_builtin_interval_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_interval_id, min_interval_id, max_interval_id, hash_id_interval_id);
            }
            if (!tmp_ann_custom_interval_id.empty())
            {
                ann_custom_Ohlcv = tmp_ann_custom_interval_id;
            }
            CompleteMemberDetail detail_interval_id = TypeObjectUtils::build_complete_member_detail(name_interval_id, member_ann_builtin_interval_id, ann_custom_Ohlcv);
            CompleteStructMember member_interval_id = TypeObjectUtils::build_complete_struct_member(common_interval_id, detail_interval_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Ohlcv, member_interval_id);
        }
        {
            TypeIdentifierPair type_ids_etime;
            ReturnCode_t return_code_etime {eprosima::fastdds::dds::RETCODE_OK};
            return_code_etime =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::timestamp_t", type_ids_etime);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_etime)
            {
                ::inclination::idl_ex::register_timestamp_t_type_identifier(type_ids_etime);
            }
            StructMemberFlag member_flags_etime = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_etime = 0x00000003;
            bool common_etime_ec {false};
            CommonStructMember common_etime {TypeObjectUtils::build_common_struct_member(member_id_etime, member_flags_etime, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_etime, common_etime_ec))};
            if (!common_etime_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure etime member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_etime = "etime";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_etime;
            ann_custom_Ohlcv.reset();
            CompleteMemberDetail detail_etime = TypeObjectUtils::build_complete_member_detail(name_etime, member_ann_builtin_etime, ann_custom_Ohlcv);
            CompleteStructMember member_etime = TypeObjectUtils::build_complete_struct_member(common_etime, detail_etime);
            TypeObjectUtils::add_complete_struct_member(member_seq_Ohlcv, member_etime);
        }
        {
            TypeIdentifierPair type_ids_data;
            ReturnCode_t return_code_data {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::OhlcvData", type_ids_data);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
            {
                ::inclination::idl_ex::register_OhlcvData_type_identifier(type_ids_data);
            }
            StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data = 0x00000004;
            bool common_data_ec {false};
            CommonStructMember common_data {TypeObjectUtils::build_common_struct_member(member_id_data, member_flags_data, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
            if (!common_data_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data = "data";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
            ann_custom_Ohlcv.reset();
            CompleteMemberDetail detail_data = TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_Ohlcv);
            CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
            TypeObjectUtils::add_complete_struct_member(member_seq_Ohlcv, member_data);
        }
        CompleteStructType struct_type_Ohlcv = TypeObjectUtils::build_complete_struct_type(struct_flags_Ohlcv, header_Ohlcv, member_seq_Ohlcv);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Ohlcv, type_name_Ohlcv.to_string(), type_ids_Ohlcv))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::Ohlcv already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_OhlcvSeries_type_identifier(
        TypeIdentifierPair& type_ids_OhlcvSeries)
{

    ReturnCode_t return_code_OhlcvSeries {eprosima::fastdds::dds::RETCODE_OK};
    return_code_OhlcvSeries =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "inclination::idl_ex::OhlcvSeries", type_ids_OhlcvSeries);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_OhlcvSeries)
    {
        StructTypeFlag struct_flags_OhlcvSeries = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_OhlcvSeries = "inclination::idl_ex::OhlcvSeries";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_OhlcvSeries;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_OhlcvSeries;
        CompleteTypeDetail detail_OhlcvSeries = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_OhlcvSeries, ann_custom_OhlcvSeries, type_name_OhlcvSeries.to_string());
        CompleteStructHeader header_OhlcvSeries;
        header_OhlcvSeries = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_OhlcvSeries);
        CompleteStructMemberSeq member_seq_OhlcvSeries;
        {
            TypeIdentifierPair type_ids_exchange_id;
            ReturnCode_t return_code_exchange_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_exchange_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_exchange_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_exchange_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_exchange_id);
            }
            StructMemberFlag member_flags_exchange_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_exchange_id = 0x00000000;
            bool common_exchange_id_ec {false};
            CommonStructMember common_exchange_id {TypeObjectUtils::build_common_struct_member(member_id_exchange_id, member_flags_exchange_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_exchange_id, common_exchange_id_ec))};
            if (!common_exchange_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure exchange_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_exchange_id = "exchange_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_exchange_id;
            ann_custom_OhlcvSeries.reset();
            AppliedAnnotationSeq tmp_ann_custom_exchange_id;
            eprosima::fastcdr::optional<std::string> unit_exchange_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_exchange_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_exchange_id;
            eprosima::fastcdr::optional<std::string> hash_id_exchange_id;
            if (unit_exchange_id.has_value() || min_exchange_id.has_value() || max_exchange_id.has_value() || hash_id_exchange_id.has_value())
            {
                member_ann_builtin_exchange_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_exchange_id, min_exchange_id, max_exchange_id, hash_id_exchange_id);
            }
            if (!tmp_ann_custom_exchange_id.empty())
            {
                ann_custom_OhlcvSeries = tmp_ann_custom_exchange_id;
            }
            CompleteMemberDetail detail_exchange_id = TypeObjectUtils::build_complete_member_detail(name_exchange_id, member_ann_builtin_exchange_id, ann_custom_OhlcvSeries);
            CompleteStructMember member_exchange_id = TypeObjectUtils::build_complete_struct_member(common_exchange_id, detail_exchange_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvSeries, member_exchange_id);
        }
        {
            TypeIdentifierPair type_ids_symbol_id;
            ReturnCode_t return_code_symbol_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_symbol_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_symbol_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_symbol_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_symbol_id);
            }
            StructMemberFlag member_flags_symbol_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_symbol_id = 0x00000001;
            bool common_symbol_id_ec {false};
            CommonStructMember common_symbol_id {TypeObjectUtils::build_common_struct_member(member_id_symbol_id, member_flags_symbol_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_symbol_id, common_symbol_id_ec))};
            if (!common_symbol_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure symbol_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_symbol_id = "symbol_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_symbol_id;
            ann_custom_OhlcvSeries.reset();
            AppliedAnnotationSeq tmp_ann_custom_symbol_id;
            eprosima::fastcdr::optional<std::string> unit_symbol_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_symbol_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_symbol_id;
            eprosima::fastcdr::optional<std::string> hash_id_symbol_id;
            if (unit_symbol_id.has_value() || min_symbol_id.has_value() || max_symbol_id.has_value() || hash_id_symbol_id.has_value())
            {
                member_ann_builtin_symbol_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_symbol_id, min_symbol_id, max_symbol_id, hash_id_symbol_id);
            }
            if (!tmp_ann_custom_symbol_id.empty())
            {
                ann_custom_OhlcvSeries = tmp_ann_custom_symbol_id;
            }
            CompleteMemberDetail detail_symbol_id = TypeObjectUtils::build_complete_member_detail(name_symbol_id, member_ann_builtin_symbol_id, ann_custom_OhlcvSeries);
            CompleteStructMember member_symbol_id = TypeObjectUtils::build_complete_struct_member(common_symbol_id, detail_symbol_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvSeries, member_symbol_id);
        }
        {
            TypeIdentifierPair type_ids_interval_id;
            ReturnCode_t return_code_interval_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_interval_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::key_t", type_ids_interval_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_interval_id)
            {
                ::inclination::idl_ex::register_key_t_type_identifier(type_ids_interval_id);
            }
            StructMemberFlag member_flags_interval_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_interval_id = 0x00000002;
            bool common_interval_id_ec {false};
            CommonStructMember common_interval_id {TypeObjectUtils::build_common_struct_member(member_id_interval_id, member_flags_interval_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_interval_id, common_interval_id_ec))};
            if (!common_interval_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure interval_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_interval_id = "interval_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_interval_id;
            ann_custom_OhlcvSeries.reset();
            AppliedAnnotationSeq tmp_ann_custom_interval_id;
            eprosima::fastcdr::optional<std::string> unit_interval_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_interval_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_interval_id;
            eprosima::fastcdr::optional<std::string> hash_id_interval_id;
            if (unit_interval_id.has_value() || min_interval_id.has_value() || max_interval_id.has_value() || hash_id_interval_id.has_value())
            {
                member_ann_builtin_interval_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_interval_id, min_interval_id, max_interval_id, hash_id_interval_id);
            }
            if (!tmp_ann_custom_interval_id.empty())
            {
                ann_custom_OhlcvSeries = tmp_ann_custom_interval_id;
            }
            CompleteMemberDetail detail_interval_id = TypeObjectUtils::build_complete_member_detail(name_interval_id, member_ann_builtin_interval_id, ann_custom_OhlcvSeries);
            CompleteStructMember member_interval_id = TypeObjectUtils::build_complete_struct_member(common_interval_id, detail_interval_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvSeries, member_interval_id);
        }
        {
            TypeIdentifierPair type_ids_etime;
            ReturnCode_t return_code_etime {eprosima::fastdds::dds::RETCODE_OK};
            return_code_etime =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "inclination::idl_ex::timestamp_t", type_ids_etime);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_etime)
            {
                ::inclination::idl_ex::register_timestamp_t_type_identifier(type_ids_etime);
            }
            StructMemberFlag member_flags_etime = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_etime = 0x00000003;
            bool common_etime_ec {false};
            CommonStructMember common_etime {TypeObjectUtils::build_common_struct_member(member_id_etime, member_flags_etime, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_etime, common_etime_ec))};
            if (!common_etime_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure etime member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_etime = "etime";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_etime;
            ann_custom_OhlcvSeries.reset();
            CompleteMemberDetail detail_etime = TypeObjectUtils::build_complete_member_detail(name_etime, member_ann_builtin_etime, ann_custom_OhlcvSeries);
            CompleteStructMember member_etime = TypeObjectUtils::build_complete_struct_member(common_etime, detail_etime);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvSeries, member_etime);
        }
        {
            TypeIdentifierPair type_ids_data;
            ReturnCode_t return_code_data {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded", type_ids_data);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
            {
                return_code_data =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "inclination::idl_ex::OhlcvData", type_ids_data);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
                {
                    ::inclination::idl_ex::register_OhlcvData_type_identifier(type_ids_data);
                }
                bool element_identifier_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, element_identifier_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_data.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded, element_flags_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded", type_ids_data))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_inclination_idl_ex_OhlcvData_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data = 0x00000004;
            bool common_data_ec {false};
            CommonStructMember common_data {TypeObjectUtils::build_common_struct_member(member_id_data, member_flags_data, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
            if (!common_data_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data = "data";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
            ann_custom_OhlcvSeries.reset();
            CompleteMemberDetail detail_data = TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_OhlcvSeries);
            CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
            TypeObjectUtils::add_complete_struct_member(member_seq_OhlcvSeries, member_data);
        }
        CompleteStructType struct_type_OhlcvSeries = TypeObjectUtils::build_complete_struct_type(struct_flags_OhlcvSeries, header_OhlcvSeries, member_seq_OhlcvSeries);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_OhlcvSeries, type_name_OhlcvSeries.to_string(), type_ids_OhlcvSeries))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "inclination::idl_ex::OhlcvSeries already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace idl_ex

} // namespace inclination

