// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ohlcv.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__INCLINATION_IDL_EX_OHLCV_HPP
#define FAST_DDS_GENERATED__INCLINATION_IDL_EX_OHLCV_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include "common.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(OHLCV_SOURCE)
#define OHLCV_DllAPI __declspec( dllexport )
#else
#define OHLCV_DllAPI __declspec( dllimport )
#endif // OHLCV_SOURCE
#else
#define OHLCV_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define OHLCV_DllAPI
#endif // _WIN32

namespace inclination {

namespace idl_ex {

typedef std::string key_t;

typedef double price_t;

typedef double volume_t;

/*!
 * @brief This class represents the structure exchange_t defined by the user in the IDL file.
 * @ingroup ohlcv
 */
class exchange_t
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport exchange_t()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~exchange_t()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object exchange_t that will be copied.
     */
    eProsima_user_DllExport exchange_t(
            const exchange_t& x)
    {
                    m_id = x.m_id;

                    m_name = x.m_name;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object exchange_t that will be copied.
     */
    eProsima_user_DllExport exchange_t(
            exchange_t&& x) noexcept
    {
        m_id = std::move(x.m_id);
        m_name = std::move(x.m_name);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object exchange_t that will be copied.
     */
    eProsima_user_DllExport exchange_t& operator =(
            const exchange_t& x)
    {

                    m_id = x.m_id;

                    m_name = x.m_name;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object exchange_t that will be copied.
     */
    eProsima_user_DllExport exchange_t& operator =(
            exchange_t&& x) noexcept
    {

        m_id = std::move(x.m_id);
        m_name = std::move(x.m_name);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x exchange_t object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const exchange_t& x) const
    {
        return (m_id == x.m_id &&
           m_name == x.m_name);
    }

    /*!
     * @brief Comparison operator.
     * @param x exchange_t object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const exchange_t& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    eProsima_user_DllExport void id(
            const key_t& _id)
    {
        m_id = _id;
    }

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    eProsima_user_DllExport void id(
            key_t&& _id)
    {
        m_id = std::move(_id);
    }

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    eProsima_user_DllExport const key_t& id() const
    {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport key_t& id()
    {
        return m_id;
    }


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }



private:

    key_t m_id;
    std::string m_name;

};
/*!
 * @brief This class represents the structure asset_t defined by the user in the IDL file.
 * @ingroup ohlcv
 */
class asset_t
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport asset_t()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~asset_t()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object asset_t that will be copied.
     */
    eProsima_user_DllExport asset_t(
            const asset_t& x)
    {
                    m_id = x.m_id;

                    m_name = x.m_name;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object asset_t that will be copied.
     */
    eProsima_user_DllExport asset_t(
            asset_t&& x) noexcept
    {
        m_id = std::move(x.m_id);
        m_name = std::move(x.m_name);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object asset_t that will be copied.
     */
    eProsima_user_DllExport asset_t& operator =(
            const asset_t& x)
    {

                    m_id = x.m_id;

                    m_name = x.m_name;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object asset_t that will be copied.
     */
    eProsima_user_DllExport asset_t& operator =(
            asset_t&& x) noexcept
    {

        m_id = std::move(x.m_id);
        m_name = std::move(x.m_name);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x asset_t object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const asset_t& x) const
    {
        return (m_id == x.m_id &&
           m_name == x.m_name);
    }

    /*!
     * @brief Comparison operator.
     * @param x asset_t object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const asset_t& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    eProsima_user_DllExport void id(
            const key_t& _id)
    {
        m_id = _id;
    }

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    eProsima_user_DllExport void id(
            key_t&& _id)
    {
        m_id = std::move(_id);
    }

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    eProsima_user_DllExport const key_t& id() const
    {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport key_t& id()
    {
        return m_id;
    }


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }



private:

    key_t m_id;
    std::string m_name;

};
/*!
 * @brief This class represents the structure symbol_t defined by the user in the IDL file.
 * @ingroup ohlcv
 */
class symbol_t
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport symbol_t()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~symbol_t()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object symbol_t that will be copied.
     */
    eProsima_user_DllExport symbol_t(
            const symbol_t& x)
    {
                    m_id = x.m_id;

                    m_base = x.m_base;

                    m_quote = x.m_quote;

                    m_name = x.m_name;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object symbol_t that will be copied.
     */
    eProsima_user_DllExport symbol_t(
            symbol_t&& x) noexcept
    {
        m_id = std::move(x.m_id);
        m_base = std::move(x.m_base);
        m_quote = std::move(x.m_quote);
        m_name = std::move(x.m_name);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object symbol_t that will be copied.
     */
    eProsima_user_DllExport symbol_t& operator =(
            const symbol_t& x)
    {

                    m_id = x.m_id;

                    m_base = x.m_base;

                    m_quote = x.m_quote;

                    m_name = x.m_name;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object symbol_t that will be copied.
     */
    eProsima_user_DllExport symbol_t& operator =(
            symbol_t&& x) noexcept
    {

        m_id = std::move(x.m_id);
        m_base = std::move(x.m_base);
        m_quote = std::move(x.m_quote);
        m_name = std::move(x.m_name);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x symbol_t object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const symbol_t& x) const
    {
        return (m_id == x.m_id &&
           m_base == x.m_base &&
           m_quote == x.m_quote &&
           m_name == x.m_name);
    }

    /*!
     * @brief Comparison operator.
     * @param x symbol_t object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const symbol_t& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    eProsima_user_DllExport void id(
            const key_t& _id)
    {
        m_id = _id;
    }

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    eProsima_user_DllExport void id(
            key_t&& _id)
    {
        m_id = std::move(_id);
    }

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    eProsima_user_DllExport const key_t& id() const
    {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport key_t& id()
    {
        return m_id;
    }


    /*!
     * @brief This function copies the value in member base
     * @param _base New value to be copied in member base
     */
    eProsima_user_DllExport void base(
            const asset_t& _base)
    {
        m_base = _base;
    }

    /*!
     * @brief This function moves the value in member base
     * @param _base New value to be moved in member base
     */
    eProsima_user_DllExport void base(
            asset_t&& _base)
    {
        m_base = std::move(_base);
    }

    /*!
     * @brief This function returns a constant reference to member base
     * @return Constant reference to member base
     */
    eProsima_user_DllExport const asset_t& base() const
    {
        return m_base;
    }

    /*!
     * @brief This function returns a reference to member base
     * @return Reference to member base
     */
    eProsima_user_DllExport asset_t& base()
    {
        return m_base;
    }


    /*!
     * @brief This function copies the value in member quote
     * @param _quote New value to be copied in member quote
     */
    eProsima_user_DllExport void quote(
            const asset_t& _quote)
    {
        m_quote = _quote;
    }

    /*!
     * @brief This function moves the value in member quote
     * @param _quote New value to be moved in member quote
     */
    eProsima_user_DllExport void quote(
            asset_t&& _quote)
    {
        m_quote = std::move(_quote);
    }

    /*!
     * @brief This function returns a constant reference to member quote
     * @return Constant reference to member quote
     */
    eProsima_user_DllExport const asset_t& quote() const
    {
        return m_quote;
    }

    /*!
     * @brief This function returns a reference to member quote
     * @return Reference to member quote
     */
    eProsima_user_DllExport asset_t& quote()
    {
        return m_quote;
    }


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }



private:

    key_t m_id;
    asset_t m_base;
    asset_t m_quote;
    std::string m_name;

};
/*!
 * @brief This class represents the structure interval_t defined by the user in the IDL file.
 * @ingroup ohlcv
 */
class interval_t
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport interval_t()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~interval_t()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object interval_t that will be copied.
     */
    eProsima_user_DllExport interval_t(
            const interval_t& x)
    {
                    m_id = x.m_id;

                    m_name = x.m_name;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object interval_t that will be copied.
     */
    eProsima_user_DllExport interval_t(
            interval_t&& x) noexcept
    {
        m_id = std::move(x.m_id);
        m_name = std::move(x.m_name);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object interval_t that will be copied.
     */
    eProsima_user_DllExport interval_t& operator =(
            const interval_t& x)
    {

                    m_id = x.m_id;

                    m_name = x.m_name;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object interval_t that will be copied.
     */
    eProsima_user_DllExport interval_t& operator =(
            interval_t&& x) noexcept
    {

        m_id = std::move(x.m_id);
        m_name = std::move(x.m_name);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x interval_t object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const interval_t& x) const
    {
        return (m_id == x.m_id &&
           m_name == x.m_name);
    }

    /*!
     * @brief Comparison operator.
     * @param x interval_t object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const interval_t& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    eProsima_user_DllExport void id(
            const key_t& _id)
    {
        m_id = _id;
    }

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    eProsima_user_DllExport void id(
            key_t&& _id)
    {
        m_id = std::move(_id);
    }

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    eProsima_user_DllExport const key_t& id() const
    {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport key_t& id()
    {
        return m_id;
    }


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }



private:

    key_t m_id;
    std::string m_name;

};
/*!
 * @brief This class represents the structure OhlcvData defined by the user in the IDL file.
 * @ingroup ohlcv
 */
class OhlcvData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport OhlcvData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~OhlcvData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object OhlcvData that will be copied.
     */
    eProsima_user_DllExport OhlcvData(
            const OhlcvData& x)
    {
                    m_timestamp = x.m_timestamp;

                    m_open = x.m_open;

                    m_high = x.m_high;

                    m_low = x.m_low;

                    m_close = x.m_close;

                    m_volume = x.m_volume;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object OhlcvData that will be copied.
     */
    eProsima_user_DllExport OhlcvData(
            OhlcvData&& x) noexcept
    {
        m_timestamp = x.m_timestamp;
        m_open = x.m_open;
        m_high = x.m_high;
        m_low = x.m_low;
        m_close = x.m_close;
        m_volume = x.m_volume;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object OhlcvData that will be copied.
     */
    eProsima_user_DllExport OhlcvData& operator =(
            const OhlcvData& x)
    {

                    m_timestamp = x.m_timestamp;

                    m_open = x.m_open;

                    m_high = x.m_high;

                    m_low = x.m_low;

                    m_close = x.m_close;

                    m_volume = x.m_volume;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object OhlcvData that will be copied.
     */
    eProsima_user_DllExport OhlcvData& operator =(
            OhlcvData&& x) noexcept
    {

        m_timestamp = x.m_timestamp;
        m_open = x.m_open;
        m_high = x.m_high;
        m_low = x.m_low;
        m_close = x.m_close;
        m_volume = x.m_volume;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x OhlcvData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const OhlcvData& x) const
    {
        return (m_timestamp == x.m_timestamp &&
           m_open == x.m_open &&
           m_high == x.m_high &&
           m_low == x.m_low &&
           m_close == x.m_close &&
           m_volume == x.m_volume);
    }

    /*!
     * @brief Comparison operator.
     * @param x OhlcvData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const OhlcvData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            timestamp_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport timestamp_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport timestamp_t& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function sets a value in member open
     * @param _open New value for member open
     */
    eProsima_user_DllExport void open(
            price_t _open)
    {
        m_open = _open;
    }

    /*!
     * @brief This function returns the value of member open
     * @return Value of member open
     */
    eProsima_user_DllExport price_t open() const
    {
        return m_open;
    }

    /*!
     * @brief This function returns a reference to member open
     * @return Reference to member open
     */
    eProsima_user_DllExport price_t& open()
    {
        return m_open;
    }


    /*!
     * @brief This function sets a value in member high
     * @param _high New value for member high
     */
    eProsima_user_DllExport void high(
            price_t _high)
    {
        m_high = _high;
    }

    /*!
     * @brief This function returns the value of member high
     * @return Value of member high
     */
    eProsima_user_DllExport price_t high() const
    {
        return m_high;
    }

    /*!
     * @brief This function returns a reference to member high
     * @return Reference to member high
     */
    eProsima_user_DllExport price_t& high()
    {
        return m_high;
    }


    /*!
     * @brief This function sets a value in member low
     * @param _low New value for member low
     */
    eProsima_user_DllExport void low(
            price_t _low)
    {
        m_low = _low;
    }

    /*!
     * @brief This function returns the value of member low
     * @return Value of member low
     */
    eProsima_user_DllExport price_t low() const
    {
        return m_low;
    }

    /*!
     * @brief This function returns a reference to member low
     * @return Reference to member low
     */
    eProsima_user_DllExport price_t& low()
    {
        return m_low;
    }


    /*!
     * @brief This function sets a value in member close
     * @param _close New value for member close
     */
    eProsima_user_DllExport void close(
            price_t _close)
    {
        m_close = _close;
    }

    /*!
     * @brief This function returns the value of member close
     * @return Value of member close
     */
    eProsima_user_DllExport price_t close() const
    {
        return m_close;
    }

    /*!
     * @brief This function returns a reference to member close
     * @return Reference to member close
     */
    eProsima_user_DllExport price_t& close()
    {
        return m_close;
    }


    /*!
     * @brief This function sets a value in member volume
     * @param _volume New value for member volume
     */
    eProsima_user_DllExport void volume(
            volume_t _volume)
    {
        m_volume = _volume;
    }

    /*!
     * @brief This function returns the value of member volume
     * @return Value of member volume
     */
    eProsima_user_DllExport volume_t volume() const
    {
        return m_volume;
    }

    /*!
     * @brief This function returns a reference to member volume
     * @return Reference to member volume
     */
    eProsima_user_DllExport volume_t& volume()
    {
        return m_volume;
    }



private:

    timestamp_t m_timestamp{0.0};
    price_t m_open{0.0};
    price_t m_high{0.0};
    price_t m_low{0.0};
    price_t m_close{0.0};
    volume_t m_volume{0.0};

};
/*!
 * @brief This class represents the structure Ohlcv defined by the user in the IDL file.
 * @ingroup ohlcv
 */
class Ohlcv
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Ohlcv()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Ohlcv()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Ohlcv that will be copied.
     */
    eProsima_user_DllExport Ohlcv(
            const Ohlcv& x)
    {
                    m_exchange_id = x.m_exchange_id;

                    m_symbol_id = x.m_symbol_id;

                    m_interval_id = x.m_interval_id;

                    m_etime = x.m_etime;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Ohlcv that will be copied.
     */
    eProsima_user_DllExport Ohlcv(
            Ohlcv&& x) noexcept
    {
        m_exchange_id = std::move(x.m_exchange_id);
        m_symbol_id = std::move(x.m_symbol_id);
        m_interval_id = std::move(x.m_interval_id);
        m_etime = x.m_etime;
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Ohlcv that will be copied.
     */
    eProsima_user_DllExport Ohlcv& operator =(
            const Ohlcv& x)
    {

                    m_exchange_id = x.m_exchange_id;

                    m_symbol_id = x.m_symbol_id;

                    m_interval_id = x.m_interval_id;

                    m_etime = x.m_etime;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Ohlcv that will be copied.
     */
    eProsima_user_DllExport Ohlcv& operator =(
            Ohlcv&& x) noexcept
    {

        m_exchange_id = std::move(x.m_exchange_id);
        m_symbol_id = std::move(x.m_symbol_id);
        m_interval_id = std::move(x.m_interval_id);
        m_etime = x.m_etime;
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Ohlcv object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Ohlcv& x) const
    {
        return (m_exchange_id == x.m_exchange_id &&
           m_symbol_id == x.m_symbol_id &&
           m_interval_id == x.m_interval_id &&
           m_etime == x.m_etime &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x Ohlcv object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Ohlcv& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member exchange_id
     * @param _exchange_id New value to be copied in member exchange_id
     */
    eProsima_user_DllExport void exchange_id(
            const key_t& _exchange_id)
    {
        m_exchange_id = _exchange_id;
    }

    /*!
     * @brief This function moves the value in member exchange_id
     * @param _exchange_id New value to be moved in member exchange_id
     */
    eProsima_user_DllExport void exchange_id(
            key_t&& _exchange_id)
    {
        m_exchange_id = std::move(_exchange_id);
    }

    /*!
     * @brief This function returns a constant reference to member exchange_id
     * @return Constant reference to member exchange_id
     */
    eProsima_user_DllExport const key_t& exchange_id() const
    {
        return m_exchange_id;
    }

    /*!
     * @brief This function returns a reference to member exchange_id
     * @return Reference to member exchange_id
     */
    eProsima_user_DllExport key_t& exchange_id()
    {
        return m_exchange_id;
    }


    /*!
     * @brief This function copies the value in member symbol_id
     * @param _symbol_id New value to be copied in member symbol_id
     */
    eProsima_user_DllExport void symbol_id(
            const key_t& _symbol_id)
    {
        m_symbol_id = _symbol_id;
    }

    /*!
     * @brief This function moves the value in member symbol_id
     * @param _symbol_id New value to be moved in member symbol_id
     */
    eProsima_user_DllExport void symbol_id(
            key_t&& _symbol_id)
    {
        m_symbol_id = std::move(_symbol_id);
    }

    /*!
     * @brief This function returns a constant reference to member symbol_id
     * @return Constant reference to member symbol_id
     */
    eProsima_user_DllExport const key_t& symbol_id() const
    {
        return m_symbol_id;
    }

    /*!
     * @brief This function returns a reference to member symbol_id
     * @return Reference to member symbol_id
     */
    eProsima_user_DllExport key_t& symbol_id()
    {
        return m_symbol_id;
    }


    /*!
     * @brief This function copies the value in member interval_id
     * @param _interval_id New value to be copied in member interval_id
     */
    eProsima_user_DllExport void interval_id(
            const key_t& _interval_id)
    {
        m_interval_id = _interval_id;
    }

    /*!
     * @brief This function moves the value in member interval_id
     * @param _interval_id New value to be moved in member interval_id
     */
    eProsima_user_DllExport void interval_id(
            key_t&& _interval_id)
    {
        m_interval_id = std::move(_interval_id);
    }

    /*!
     * @brief This function returns a constant reference to member interval_id
     * @return Constant reference to member interval_id
     */
    eProsima_user_DllExport const key_t& interval_id() const
    {
        return m_interval_id;
    }

    /*!
     * @brief This function returns a reference to member interval_id
     * @return Reference to member interval_id
     */
    eProsima_user_DllExport key_t& interval_id()
    {
        return m_interval_id;
    }


    /*!
     * @brief This function sets a value in member etime
     * @param _etime New value for member etime
     */
    eProsima_user_DllExport void etime(
            timestamp_t _etime)
    {
        m_etime = _etime;
    }

    /*!
     * @brief This function returns the value of member etime
     * @return Value of member etime
     */
    eProsima_user_DllExport timestamp_t etime() const
    {
        return m_etime;
    }

    /*!
     * @brief This function returns a reference to member etime
     * @return Reference to member etime
     */
    eProsima_user_DllExport timestamp_t& etime()
    {
        return m_etime;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const OhlcvData& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            OhlcvData&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const OhlcvData& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport OhlcvData& data()
    {
        return m_data;
    }



private:

    key_t m_exchange_id;
    key_t m_symbol_id;
    key_t m_interval_id;
    timestamp_t m_etime{0.0};
    OhlcvData m_data;

};

} // namespace idl_ex

} // namespace inclination

#endif // _FAST_DDS_GENERATED_INCLINATION_IDL_EX_OHLCV_HPP_


